name: Merge

on:
  push:
    branches: ["main"]
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Amsterdam"

      - uses: actions/checkout@v4

      - uses: gerlero/apt-install@v1
        with:
          packages: build-essential git libcurl4-openssl-dev curl libssl-dev
          install-recommends: false

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Install application requirements (pip)
        run: uv sync

      - name: Build
        run: uv build

      - run: echo "TAG=$(python -c 'from notifications_utils.version import __version__; print(__version__)')" >> $GITHUB_ENV
        name: Set tag
        id: set-tag

      - uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          custom_tag: ${{ env.TAG }}
        name: Create git tag

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          make_latest: true
        name: Create Github release
